// TRASNPORT MEANS HOW THE SERVICE IS CALLED HOW THE SERVICE IS CALLED //

//E.G HTTP(OVER THE WEB TRANSPORT)AND MQ(OVER THE Q E.G MQ)

//TRANSPORT WETHER THE SERVICE IS EXPOSED OVER A MQ OR Q OR HTTP//


