// WHAT ARE WEBSERVICES AND WHAT DO THEY DO OR MEAN//


// 3 KEYS ASPECTS OF WEBSERVICES INCLUDE//

// WEBSERVICES ARE ABLE TO COMMUNICATE BETWEEN MACHINES/ MACHINE TO MACHINE COMMUNICATION OR APPLICATION TO APPLICATION INTERCATION//
// WEBSERVICES SHOULD BE INTEROPERABLE - NOT PLATFORM DEPANDENT ANY OTHER APPLICATION SHOULD BE ABLE TO TALK TO YOUR WEBSITES OF APPS EG CONNECTIONS BETWEENS APPLICATIONS BUILT WITH JAVASCRIPT AND .NETCORE OR PHP OR GOLANG//


// SHOULD ALLOW COMMUNICATION OVER A NETWORK WHICH MEANS AN APPLICATION CAN COMMUNICATION ACORSS LOCATIONS OVER ANY GIVEN NETWORK NOT ONLY LOCALLY   //

// INPUT TO A WEBSERVICE IS CALLED A REQUEST//
//OUTPUT TO A WEBSERVICE IS CALLED A RESPONSE//


// WEBSERVICES SHOULD BE PLATFORM INDPENDENT WHICH MEANS//

// WE SHOULD BE ABLE TO CALL IT FROM 
// A JAVA APPLICATION
// A DOTNET APPLICATION
// PHP APPLICAION

// JSON JAVASCRIPT OBJECT NOTATION




